// with-svelte/contents/plasmo-overlay.svelte
<script context="module" lang="ts">
  import cssText from "data-text:~/contents/plasmo-overlay.css"
  import type { PlasmoContentScript } from "plasmo"

  export const config: PlasmoContentScript = {
    matches: ["https://www.plasmo.com/*"]
  }

  export const getStyle = () => {
    const style = document.createElement("style")
    style.textContent = cssText
    return style
  }
</script>

<span class="hw-top"> HELLO WORLD TOP </span>

// with-content-scripts-ui/contents/plasmo-overlay.tsx
import cssText from "data-text:~/contents/plasmo-overlay.css"
import type { PlasmoCSConfig } from "plasmo"

export const config: PlasmoCSConfig = {
  matches: ["https://www.plasmo.com/*"],
  css: ["font.css"]
}

export const getStyle = () => {
  const style = document.createElement("style")
  style.textContent = cssText
  return style
}

const PlasmoOverlay = () => {
  return (
    <span
      className="hw-top"
      style={{
        padding: 12
      }}>
      HELLO WORLD TOP
    </span>
  )
}

export default PlasmoOverlay
